# Generated by Django 2.1.2 on 2018-10-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interessados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('id_telegram', models.CharField(max_length=20, verbose_name='Id Telegram')),
                ('assunto_votado', models.CharField(max_length=50, verbose_name='Assunto Votado')),
            ],
        ),
        migrations.CreateModel(
            name='Locais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=30, verbose_name='Local')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('data', models.DateField(verbose_name='Data do Workshop')),
            ],
        ),
        migrations.CreateModel(
            name='Palestrantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palestrante', models.CharField(max_length=100, verbose_name='Palestrantes')),
                ('id_telegram', models.CharField(max_length=20, verbose_name='Id Telegram')),
            ],
        ),
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop', models.CharField(max_length=50, verbose_name='Workshop')),
                ('votos', models.CharField(max_length=4, verbose_name='Votos')),
                ('agendado', models.BooleanField(default=False)),
                ('realizado', models.BooleanField(default=False)),
                ('num_participantes', models.CharField(max_length=4, verbose_name='Número de Participantes')),
            ],
        ),
    ]
