# Generated by Django 2.1.2 on 2018-10-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interessados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('id_telegram', models.CharField(blank=True, default='0', max_length=20, verbose_name='Id Telegram')),
                ('assunto_votado', models.CharField(blank=True, max_length=50, verbose_name='Assunto Votado')),
                ('data_votacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data da Votação')),
            ],
            options={
                'verbose_name_plural': 'interessados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Locais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(blank=True, max_length=30, null=True, verbose_name='Local')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('data', models.DateField(verbose_name='Data do Workshop')),
                ('hora', models.TimeField(verbose_name='Hora do Workshop')),
            ],
            options={
                'verbose_name_plural': 'locais',
                'ordering': ['local'],
            },
        ),
        migrations.CreateModel(
            name='Palestrantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palestrante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Palestrantes')),
                ('id_telegram', models.CharField(blank=True, default='0', max_length=20, verbose_name='Id Telegram')),
            ],
            options={
                'verbose_name_plural': 'palestrantes',
                'ordering': ['palestrante'],
            },
        ),
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop', models.CharField(blank=True, max_length=50, null=True, verbose_name='Workshop')),
                ('votos', models.CharField(blank=True, default='0', max_length=4, null=True, verbose_name='Votos')),
                ('agendado', models.BooleanField(default=False)),
                ('realizado', models.BooleanField(default=False)),
                ('total_participantes', models.CharField(blank=True, default='0', max_length=4, verbose_name='Total de Participantes')),
            ],
            options={
                'verbose_name_plural': 'workshops',
                'ordering': ['workshop'],
            },
        ),
    ]
