# Generated by Django 2.1.2 on 2018-11-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=30)),
                ('script', models.TextField()),
                ('output', models.TextField()),
            ],
            options={
                'verbose_name': 'interação',
                'verbose_name_plural': 'interações',
                'db_table': 'interactions',
                'ordering': ['input'],
            },
        ),
        migrations.CreateModel(
            name='Interessados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('id_telegram', models.CharField(max_length=20, verbose_name='Id Telegram')),
                ('assunto_votado', models.CharField(max_length=50, verbose_name='Assunto Votado')),
                ('data_votacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Votação')),
            ],
            options={
                'verbose_name': 'interessado',
                'verbose_name_plural': 'interessados',
                'db_table': 'interessados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Locais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(blank=True, max_length=30, null=True, verbose_name='Local')),
                ('endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data do Workshop')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora do Workshop')),
            ],
            options={
                'verbose_name': 'local',
                'verbose_name_plural': 'locais',
                'db_table': 'locais',
                'ordering': ['local'],
            },
        ),
        migrations.CreateModel(
            name='Palestrantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palestrante', models.CharField(max_length=100, verbose_name='Palestrantes')),
                ('id_telegram', models.CharField(max_length=20, verbose_name='Id Telegram')),
            ],
            options={
                'verbose_name': 'palestrante',
                'verbose_name_plural': 'palestrantes',
                'db_table': 'palestrantes',
                'ordering': ['palestrante'],
            },
        ),
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop', models.CharField(max_length=50, verbose_name='Workshop')),
                ('votos', models.CharField(blank=True, max_length=4, null=True, verbose_name='Votos')),
                ('agendado', models.BooleanField(default=False)),
                ('realizado', models.BooleanField(default=False)),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data do Workshop')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora do Workshop')),
                ('total_participantes', models.CharField(blank=True, max_length=4, null=True, verbose_name='Total de Participantes')),
            ],
            options={
                'verbose_name': 'workshop',
                'verbose_name_plural': 'workshops',
                'db_table': 'workshops',
                'ordering': ['workshop'],
            },
        ),
    ]
