# Generated by Django 2.1.2 on 2018-11-03 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181102_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='locais',
            name='dados_contato',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dados do Contato'),
        ),
        migrations.AddField(
            model_name='locais',
            name='nome_contato',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Contato'),
        ),
        migrations.AddField(
            model_name='workshops',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endwork', to='core.Locais'),
        ),
        migrations.AddField(
            model_name='workshops',
            name='local',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locwork', to='core.Locais'),
        ),
        migrations.AddField(
            model_name='workshops',
            name='palestrantes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Palestrantes', verbose_name='palestrantes'),
        ),
        migrations.AlterField(
            model_name='workshops',
            name='data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datawork', to='core.Locais'),
        ),
        migrations.AlterField(
            model_name='workshops',
            name='hora',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horawork', to='core.Locais'),
        ),
    ]
