# Generated by Django 2.1.2 on 2018-11-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181103_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshops',
            name='total_participantes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Total de Participantes'),
        ),
        migrations.AlterField(
            model_name='workshops',
            name='votos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Votos'),
        ),
    ]
