# Generated by Django 2.1.2 on 2018-11-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181103_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palestrantes',
            name='id_telegram',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Id Telegram'),
        ),
    ]
