# Generated by Django 2.1.2 on 2018-11-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181103_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interessados',
            name='id_telegram',
            field=models.PositiveIntegerField(verbose_name='Id Telegram'),
        ),
    ]
